<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <StartupObject>SwitchWindowStyleSample.Program</StartupObject>
  </PropertyGroup>

  <PropertyGroup Condition="'$(OS)' == 'Windows_NT'">
    <DefineConstants>WINDOWS</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(OS)' != 'Windows_NT'">
    <OutputType>Exe</OutputType>
    <UseWPF>false</UseWPF>
  </PropertyGroup>

  <ItemGroup Condition="'$(OS)' != 'Windows_NT'">
    <Compile Remove="App.xaml.cs" />
    <Page Remove="App.xaml" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="sample.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>